### ISSUE TITLE
Demo website is not available

### ISSUE THREAD

**Issue by mekkiamiri** [Hacker0x01/react-datepicker#2650] opened 2021-01-11 13:44 UTC
Hello,
I am trying to use react-datepicker in my reactjs app.
Unfortunately, the demo website https://reactdatepicker.com/ is not available.
I get these errors:
`react-dom.production.min.js:209 Error: Minified React error #321; visit https://reactjs.org/docs/error-decoder.html?invariant=321 for the full message or use the non-minified dev environment for full errors and additional helpful warnings.
    at B (react.production.min.js:19)
    at Object.a.useState (react.production.min.js:25)
    at i (Manager.js:7)
    at Gr (react-dom.production.min.js:153)
    at ho (react-dom.production.min.js:261)
    at us (react-dom.production.min.js:246)
    at os (react-dom.production.min.js:246)
    at Jo (react-dom.production.min.js:239)
    at qo (react-dom.production.min.js:230)
    at Fs (react-dom.production.min.js:281)
Ji @ react-dom.production.min.js:209
react-dom.production.min.js:256 Uncaught Error: Minified React error #321; visit https://reactjs.org/docs/error-decoder.html?invariant=321 for the full message or use the non-minified dev environment for full errors and additional helpful warnings.
    at B (react.production.min.js:19)
    at Object.a.useState (react.production.min.js:25)
    at i (Manager.js:7)
    at Gr (react-dom.production.min.js:153)
    at ho (react-dom.production.min.js:261)
    at us (react-dom.production.min.js:246)
    at os (react-dom.production.min.js:246)
    at Jo (react-dom.production.min.js:239)
    at qo (react-dom.production.min.js:230)
    at Fs (react-dom.production.min.js:281)`

Thanks in advance,

**Comment by martijnrusschen** [comment] 2021-01-11 13:56
This is a duplicate of https://github.com/Hacker0x01/react-datepicker/issues/2647

**Closed by martijnrusschen** 2021-01-11 13:56 UTC
