### ISSUE TITLE
I can't start weeks from Monday

### ISSUE THREAD

**Issue by ledeneveugene** [Hacker0x01/react-datepicker#3125] opened 2021-08-06 16:13 UTC
**Describe the bug**
Weeks start from Sunday for ru and default locale.
You can see this problem in codesandbox (link below)

**To Reproduce**
[codesandbox](https://codesandbox.io/s/datepicker-problem-locale-8y9le?file=/src/App.js)

**Comment by Amwam** [comment] 2021-08-10 13:57
@ledeneveugene This may have been fixed in in v4.2, released 2 days ago.

Possibly a duplicate of https://github.com/Hacker0x01/react-datepicker/issues/3015

**Closed** 2021-08-10 14:30 UTC
