### ISSUE TITLE
"Today" button selects yesterday

### ISSUE THREAD

**Issue by gilomen2** [Hacker0x01/react-datepicker#660] opened 2016-12-02 21:35 UTC
I have the datepicker implemented as seen below. Everytime I click the "Today" button, the date in the input field fills in correctly, but the selected date and the state for date is always yesterday's date.

```
export class DailyTotal extends React.Component {
  constructor(props) {
    super(props);
    this.state = {
      date: moment()
    };
  }

  changeDate(date) {
    this.setState({
      date: date
    })
  }

  render() {
    return (
      <DatePicker className="input-field" selected={this.state.date} todayButton={"Today"} onChange={this.changeDate.bind(this)} />
    )
  }
}
```

**Comment by jochenberger** [comment] 2016-12-05 13:57
Probably similar to #507.

**Comment by martijnrusschen** [comment] 2016-12-05 14:31
Closing as a duplicate of #507.

**Closed by martijnrusschen** 2016-12-05 14:31 UTC

**Comment by nileshdjadhav** [comment] 2020-09-11 17:17
// common.js file
export const adjustTimezone = (date) => {
    return new Date(date.setMinutes(date.getMinutes() - date.getTimezoneOffset()));
}

// MyComponent.js
<ReactDatePicker
    dateFormat="dd/MM/yyyy"
    onChange={(value) =>
        onChange(
            adjustTimezone(value)
        )
    }
    onBlur={onBlur}
    selected={value}
    className={styles.calender}
    placeholderText="DD/MM/YYYY"
/>
