### ISSUE TITLE
Problem with react-onclickoutside

### ISSUE THREAD

**Issue by bekerov** [Hacker0x01/react-datepicker#434] opened 2016-03-30 15:12 UTC
Hello. Thanx for awesome lib.
I have i div, which render in some cases. It contains datepicker. And when i'm trying choose date, onclickoutside function fire, and my div with datepicker hiding.
I see its render at body ends. And i cant set className to calendar. 
Please help

**Comment by rafeememon** [comment] 2016-03-31 10:36
Probably a dupe of #433

**Closed by rafeememon** 2016-03-31 10:36 UTC

**Comment by vguzev** [comment] 2016-04-04 11:46
@rafeememon Please, reopen this issue, because #433 is about completely different thing...
When you do some UI action in react-datepicker component (e.g. selecting a date or switching a month) it looks like that the react-datepicker is closing calendar using react-onclickoutside functionality.
In cases when react-datepicker is embedded in filter panels (like in this screenshot http://clip2net.com/s/3wthcf2) this causes the whole panel to close. Just because this panel is also depending on react-onclickoutside...

**Comment by rafeememon** [comment] 2016-04-04 11:54
What about setting `renderCalendarTo` to the panel so that it renders there instead of `body`?

**Comment by bekerov** [comment] 2016-04-04 12:28
I cant find samples.
This not work `ReactDOM.findDOMNode(this.refs.calendar)`
Also find same question
https://github.com/souporserious/react-tether/issues/14

**Comment by rafeememon** [comment] 2016-04-05 06:55
@bekerov, @vguzev, if setting `renderCalendarTo` doesn't work please create a sample app that demonstrates the problem so we can look into it

**Comment by montogeek** [comment] 2016-04-06 15:03
I am getting the same problem

**Comment by rafeememon** [comment] 2016-04-06 16:15
@montogeek, see my comment above yours

**Comment by bekerov** [comment] 2016-04-08 07:36
I dont know which property should work. I just want ask, what i should specify in `renderCalendarTo`.
I cant find any samples and docs.

**Comment by montogeek** [comment] 2016-04-08 14:08
@bekerov If you follow the docs, `renderCalendarTo` uses `renderElementTo` on the `TetherComponent`, then it will use that element to append the component (https://github.com/souporserious/react-tether/blob/master/src/TetherComponent.jsx#L110), as you can see it accepts any `DOM Node` element (https://developer.mozilla.org/en-US/docs/Web/API/Node/appendChild)

What I dont know is how you can select a DOM Node element

**Comment by bekerov** [comment] 2016-04-11 08:03
I'm trying use 

```
<DatePicker ref='picker'
    onChange={this.onChange}
    renderCalendarTo={ReactDOM.findDOMNode(this.refs.calendar)}
    />
<div ref='calendar'></div>
```

but it still rendering to `document.body`

**Comment by bekerov** [comment] 2016-04-15 07:16
please, update this https://www.npmjs.com/package/react-tether

**Comment by bekerov** [comment] 2016-04-20 08:38
@rafeememon im tried but i have depencies conflicts

**Comment by rafeememon** [comment] 2016-04-20 16:10
Yup, see #444 #451
