### ISSUE TITLE
Datepicker won't close when clicking certain elements "gif included"?

### ISSUE THREAD

**Issue by a-eid** [Hacker0x01/react-datepicker#1136] opened 2017-11-11 12:34 UTC
probably the gif explains it way better that I would 

![](https://camo.githubusercontent.com/4430679d694d99d6a90c5783284f085c6a7682dd/68747470733a2f2f6d656469612e67697068792e636f6d2f6d656469612f78554f78663349645a426e4665424a3773512f67697068792e676966)

anybody have an idea why this would be happening?

thanks

**Comment by aij** [comment] 2017-11-12 05:42
Do the other components happen to be `react-select`?

**Comment by a-eid** [comment] 2017-11-12 06:54
Yes it is

**Comment by rafeememon** [comment] 2017-11-12 15:23
Unfortunately this is a known issue: https://github.com/Hacker0x01/react-datepicker/issues/730

**Comment by martijnrusschen** [comment] 2017-11-13 08:52
Duplicate of #730

**Closed by martijnrusschen** 2017-11-13 08:52 UTC
