### ISSUE TITLE
Only one Day is selected in week picker if week starts on monday

### ISSUE THREAD

**Issue by mbasakCinedigmInd** [Hacker0x01/react-datepicker#4625] opened 2024-03-20 12:46 UTC
Only one Day is selected in week picker if week starts on monday. i am using the following code.

<DatePicker
    selected={startDate}
    onChange={(date) => setStartDate(date)}
    dateFormat="I/R"
    calendarStartDay={1}
    showWeekNumbers
    showWeekPicker
  />

this is what it shows 
![datepicker issue](https://github.com/Hacker0x01/react-datepicker/assets/121852883/0481ebc9-f698-4e8e-bf57-da9442d218d2)

please help!!

**Comment by yuki0410-dev** [comment] 2024-03-20 23:14
@mbasakCinedigmInd
It appears to be a duplicate of #4455. (Fixed in ver 6.6.0 or later.)

**Comment by mbasakCinedigmInd** [comment] 2024-03-21 08:41
thank you.. it is solved in the new version

**Closed** 2024-03-21 08:42 UTC
