### ISSUE TITLE
Doesn't working on React 16

### ISSUE THREAD

**Issue by IftekherSunny** [Hacker0x01/react-datepicker#1060] opened 2017-10-08 06:02 UTC
hey, I can't use your package on React 16. Do you guys have any plan for supporting React 16????

**Comment by mmcshinsky** [comment] 2017-10-10 16:40
I have a working version of React 16 on a personal project with TimeSelect working as selected. Do you have example code that you can provide that we can see?

**Comment by acierto** [comment] 2017-10-12 09:01
Same here, when I select a date, I have such error

<img width="720" alt="screen shot 2017-10-12 at 11 01 27" src="https://user-images.githubusercontent.com/2265094/31488029-bd639e84-af3c-11e7-81d8-06a5e4b6e464.png">

**Comment by josegers** [comment] 2017-10-12 13:59
We have the same problem. Is there an update planned to support React 16?

**Comment by antonigiske** [comment] 2017-10-19 11:12
It works if you update yarn. I had the same problem with older version of yarn.

**Comment by aij** [comment] 2017-10-20 21:40
Duplicate of #972

**Closed** 2017-11-12 21:03 UTC
