### ISSUE TITLE
v2.20.0 of date-fns seems to break react-datepicker

### ISSUE THREAD

**Issue by marchaos** [Hacker0x01/react-datepicker#2870] opened 2021-04-08 10:26 UTC
**Describe the bug**
We upgraded to v2.20.0 of date-fns which causes "TypeError: Cannot read property 'locale' of null". Hard to trace what actually caused this issue in date-fns - the offending call is this:

```
getWeek(e,r ? { locale : r } : null)
```

It looks as though prior to v2.20.0, the second arg to getWeek did not have a default value and now it defaults to `{}`. Since null is being passed here, that won't use the default value and further down the call stack in getWeek(), it calls getWeekYear() which assumes that options will be defaulted to {} which then causes the error.

```
TypeError: Cannot read property 'locale' of null

10:03:42       at getWeekYear (../node_modules/date-fns/getWeekYear/index.js:66:24)
10:03:42       at startOfWeekYear (../node_modules/date-fns/startOfWeekYear/index.js:68:33)
10:03:42       at getWeek (../node_modules/date-fns/getWeek/index.js:65:81)
10:03:42       at Se (../node_modules/react-datepicker/dist/index.js:1:6776)
10:03:42       at n.formatWeekNumber (../node_modules/react-datepicker/dist/index.js:1:27625)
10:03:42       at n.renderDays (../node_modules/react-datepicker/dist/index.js:1:27729)
10:03:42       at n.value (../node_modules/react-datepicker/dist/index.js:1:29083)
```

**To Reproduce**

Seems to be happening when we show the date picker. Worth mentioning that this is happening in our tests (causing failures) which uses react-testing-library and js-dom

**Expected behavior**
No TypeErrors should occur

- OS: Windows
- Browser js-dom

**Comment by mcat95** [comment] 2021-04-08 15:32
Can confirm, after removing `node_modules`, `package-lock.json` and doing a clean `npm install`, version 2.20.0 of date-fns gets installed and we can reproduce this crash

**Comment by viphuangwei** [comment] 2021-04-08 18:53
We encountered the same issue today.  "v2.20.0 of date-fns seems to break react-datepicker ". it would crash the whole page.

**Comment by neerajkhaturia** [comment] 2021-04-08 18:58
We are facing the exact same issue. Please provide any temporary fix till we have a permanent solution. Thanks.

**Comment by mcat95** [comment] 2021-04-08 19:26
We fixed the issue by adding the following lines to the package.json
```
  "resolutions": {
    "date-fns": "2.19.0"
  },
```
Please, keep in mind this is a temporary fix and you should remove it as soon as this library gets a fix

**Comment by anthonywebb** [comment] 2021-04-09 16:29
Boy, aren't the 739,604 who downloaded and installed it this week in for a surprise when their production apps all hard crash the page when someone focuses on a date picker field...

**Comment by martijnrusschen** [comment] 2021-04-09 18:48
Did anyone check what changed in v2.20 that breaks the datepicker? Would be happy to accept any PRs that fix the issue.

**Comment by marchaos** [comment] 2021-04-09 20:02
> Did anyone check what changed in v2.20 that breaks the datepicker? Would be happy to accept any PRs that fix the issue.

Did you read my original comment?

**Comment by stephen-p-richard** [comment] 2021-04-10 11:24
date-fns getWeekOfYear has changed to use TypeScript and now its options var is set up like this:

`var options = arguments.length > 1 && arguments[1] !== undefined ? arguments[1] : {};`

whereas before 2.20 it was this:

`var options = dirtyOptions || {};`

So since datepicker is passing null when locale is absent, the second argument isn't undefined and
`var locale = options.locale;` in getWeekOfYear with null options is causing the TypeError.

Perhaps date-fns should be encouraged to go back to a truthy check?

**Comment by samuelcastro** [comment] 2021-04-10 22:38
Same issue, any feedback?

**Comment by toanqc** [comment] 2021-04-11 23:41
We got the same issue in our testing environment on Friday.

The below fix from @mishaseniv works for me as well. If anyone has the English version just change 'es' to 'enUS'. Hopefully, we will get the fix soon.

`import { registerLocale } from  "react-datepicker";
import es from 'date-fns/locale/es';
registerLocale('es', es)

<DatePicker
  locale="es"
/>`

**Comment by stephen-p-richard** [comment] 2021-04-12 07:49
For US English the import is from `'date-fns/locale/en-US'` - see https://github.com/date-fns/date-fns/tree/master/src/locale for all the locales.

**Comment by stephen-p-richard** [comment] 2021-04-12 08:35
It looks like this should not be a problem in 3.5.0 or higher when date_utils was changed to use date-fns.getISOWeek instead of getWeek, but it would be worth tidying the call at line 200:
`return getISOWeek(date, localeObj ? { locale: localeObj } : null);`
since getISO Week only takes a date argument.

**Comment by martijnrusschen** [comment] 2021-04-12 19:39
Can someone confirm this works fine in v3.5.0 or higher?

**Comment by xrpza** [comment] 2021-04-12 21:21
It looks like there is another break related to passing an existing date to the "selected" parameter as a string in the DatePicker component:
`Starting with v2.0.0-beta.1 date-fns doesn't accept strings as date arguments. Please use `parseISO` to parse strings. See: https://git.io/fjule`

**Comment by aaa-paul** [comment] 2021-04-13 01:57
Depending on your situation and which version of `react-datepicker` you're using (we're still using `^2.7.0` I also found that using a version prior to `2.20.0` for date-fns (like `~2.19.0`) will do the trick, no locale pieces of code needed.

**Comment by aaa-paul** [comment] 2021-04-13 03:41
Depending on your situation and which version of `react-datepicker` you're using (like `^2.7.0`) I also found that using a version prior to `2.20.0` for `date-fns` (like `~2.19.0`) will do the trick.

**Comment by xameeramir** [comment] 2021-04-13 09:25
I have `"date-fns": "^1.30.1"` and `"react-datepicker": "^2.0.0"` which seems quite older version to me.

I implemented the `<DatePicker locale="en-US" />` but the error remains:

> Uncaught TypeError: Cannot read property 'locale' of null
>     at KVYb.t.default (bundle.c57cb646.js:1)
>     at t.default (bundle.c57cb646.js:1)
>     at CYFM.t.default (bundle.c57cb646.js:1)
>     at bundle.c57cb646.js:1
>     at r.formatWeekNumber (bundle.c57cb646.js:1)
>     at r.renderDays (bundle.c57cb646.js:1)
>     at r.value (bundle.c57cb646.js:1)
>     at Ho (bundle.c57cb646.js:1)
>     at Fo (bundle.c57cb646.js:1)
>     at ys (bundle.c57cb646.js:1)

**Comment by kossnocorp** [comment] 2021-04-15 07:43
We've shipped `date-fns@v2.21.1` with [a fix for this problem](https://github.com/date-fns/date-fns/pull/2423). We've rolled back usage of the default argument value syntax for options. We will reintroduce that in v3, but as a breaking change this time. Sorry for the trouble, everyone!

**Comment by martijnrusschen** [comment] 2021-04-15 09:54
Thanks @kossnocorp!

**Comment by hutchy2570** [comment] 2021-04-16 09:58
Can confirm `date-fns@v2.21.1` has fixed this for us.

**Comment by martijnrusschen** [comment] 2021-04-16 09:58
Closing as this has been fixed.

**Closed by martijnrusschen** 2021-04-16 09:58 UTC
Labels: bug, help wanted
