### ISSUE TITLE
Positioning of calendar breaks when months have different week sizes

### ISSUE THREAD

**Issue by felipe-gdr** [Hacker0x01/react-datepicker#575] opened 2016-10-05 14:54 UTC
When navigating between months, the calendar container keeps changing position. 

This only happens when the calendar is above the input field.

![nov](https://cloud.githubusercontent.com/assets/3858115/19118236/36e48220-8af2-11e6-9f1b-06562b1c23bd.png)
![mar](https://cloud.githubusercontent.com/assets/3858115/19118242/3d1e9cac-8af2-11e6-9e22-b378f20770b9.png)
![apr](https://cloud.githubusercontent.com/assets/3858115/19118245/3ec7c376-8af2-11e6-886c-e47e281a6867.png)

**Comment by rafeememon** [comment] 2016-10-05 15:04
Dupe of #361

**Closed by rafeememon** 2016-10-05 15:04 UTC
