### ISSUE TITLE
RangeError: Invalid time value, when clearing the input field

### ISSUE THREAD

**Issue by NemanjaTck** [Hacker0x01/react-datepicker#2181] opened 2020-06-12 07:12 UTC
Clearing the input field and then clicking somewhere outside the datepicker breaks the application with the following error
- RangeError: Invalid time value

**To Reproduce**
1. Clear the input field of the datepicker
2. Click somewhere outside of the field 

**Expected behavior**
Accepting null/undefined values or reseting to the previous value

**Screenshots**
![image](https://user-images.githubusercontent.com/3010324/84475382-bfb60f00-ac8c-11ea-9e15-2b70469a8155.png)

**Comment by seangibbens** [comment] 2020-06-16 14:42
Issue occurs when clearing via the keyboard, and also clearing via the `isClearable` button.

**Comment by SeokhwanWon** [comment] 2020-08-25 02:25
me too

**Comment by chrifmarwen** [comment] 2020-11-20 07:51
We have encountred the same issue and landed here,

but after some experimentation, our problem cames from setting an invalid value passed to the "selected" props
(invalid moment date with toDate())

**Closed** 2021-06-18 22:50 UTC
Labels: wontfix

**Comment by pellea** [comment] 2022-03-24 08:37
Why is this close? The issue is still there in the latest version.

**Comment by MaxLeiter** [comment] 2022-03-31 05:55
I agree, I'm also running into this.

**Comment by Desintegrator** [comment] 2022-04-22 12:11
same
