### ISSUE TITLE
Date picker not closed after date selection.

### ISSUE THREAD

**Issue by kaushikbarodiya** [Hacker0x01/react-datepicker#597] opened 2016-10-20 08:15 UTC
If I change the month and then select the date sometime calendar doesn't close.
To replicate the issue change month and select date.
For mobile browser, it doesn't close always.

**Comment by rafeememon** [comment] 2016-10-21 13:51
Does this work on the demo site?  Are there any console errors?  Can you link to an app that shows this problem?

**Comment by andreechristian** [comment] 2016-10-24 04:12
It is happening to me on mobile only.. After a little debugging, i found these functions triggering on desktop (the correct one):
`handleBlur`
`deferFocusInput`
`cancelFocusInput` 
`handleFocus` -> most likely from deferFocusInput -> setOpen : true
`handleSelect` -> setOpen : false

while in mobile i got following order :
`handleBlur`
`deferFocusInput`
`cancelFocusInput` 
`handleSelect` -> setOpen : false
`handleFocus` -> most likely from deferFocusInput -> setOpen : true

**Comment by kaushikbarodiya** [comment] 2016-10-25 18:19
Yeah this issue persist only in mobile. On desktop it works fine.

**Comment by kaushikbarodiya** [comment] 2016-10-25 18:23
There were no console errors. You can recreate the problem on example site
itself.

1. Toggle the device from web to mobile.
2. Try to select date in first example itself.You will find date picker
doesn't close after selecting particular date.

Please let me know in case you are not able to recreate.

**Comment by cyrusbowman** [comment] 2016-11-06 21:51
+1 I have the same issue, I am NOT on mobile. I'm almost positive the date selector used to close after selecting a date in earlier versions. Also note if using a custom input it DOES close after selecting a date.

Not Closing After Selection:
![Not Closing After Selection](https://cloud.githubusercontent.com/assets/2474343/20042038/d9d579fa-a440-11e6-8240-5a29827e6c06.gif)

Custom Input DOES Close After Selection:
![Custom Input DOES Close After Selection](https://cloud.githubusercontent.com/assets/2474343/20042043/efe1f02a-a440-11e6-80ff-1d1760df2fde.gif)

**Comment by mahammedzkhan** [comment] 2016-11-08 12:19
Maybe it's better to add a property which allows it to stay open when you select a date? On false it should just autoclose.

**Comment by kaushikbarodiya** [comment] 2016-11-09 06:20
Yes, I liked the idea of Mahammed. In this way we will have more control
over the component.

**Comment by splendidtrade** [comment] 2016-12-04 22:37
@kaushikbarodiya: were you able to solve this issue on mobile, please let me know.

**Comment by timwilkbrandt** [comment] 2016-12-07 20:24
I had the same problem, further compounding my ordeal was that we're using typescript and the react-datepicker component does not have the complete suite of typings available. In lieu of creating my own typings I decided to leverage what i had available, which basically boiled down to the onChange event and the refs. 

this led to the following solution within the onChange eventHandler: 

this.props.handleStartDateChange(date) //saving date to state
      let temp = this
      setTimeout(function(){
      if (temp.refs.datepicker1.refs.calendar) {
           temp.refs.datepicker1.refs.calendar.handleClickOutside()
      }
      }, 500)

Hope this helps someone.

**Comment by jvarshaprdxn** [comment] 2017-03-22 05:47
I am also facing the same issue on Android and IOS, date pickers are not getting close after date selection,  it gives the flicker effect after choosing date but it dosen't close.

**Comment by timwilkbrandt** [comment] 2017-03-22 15:57
@jvarshaprdxn you can either use the trick i listed above, but that was more due to the fact that I was using typescript and the typings did not support custom input. Or you can use the custom input type which we tested on the ipad and appeared to work:
https://hacker0x01.github.io/react-datepicker/#example-29
Best of luck,
Tim

**Comment by jvarshaprdxn** [comment] 2017-03-23 16:05
@timwilkbrandt Thanks.
I have updated to version 0.43 and it is working now properly as expected.

**Comment by dfahlander** [comment] 2018-03-28 19:55
This happens for me on chrome desktop. After navigating to next month and clicking a date, the onChange event does not trigger, but the calendar quickly closes and reopens. Then clicking a second time triggers the change event and calendar is closed. I am on version 1.3.0. Also had the issue on version 1.2.1. Not tested earlier versions. React popper versions: 0.8.2 and 0.8.3.

**Comment by dfahlander** [comment] 2018-03-28 20:15
I've narrowed down the issue to reproduce it. It's actually even reproducable on the project's main page example.

Repro:
1. Use Chrome or Opera (not tested other browsers)
2. Go to https://reactdatepicker.com
3. Make your browser-window small, so that the calendar needs to show over the input field instead of under it.
4. Navigate to September 2018:
![image](https://user-images.githubusercontent.com/6791329/38053766-3cd1e060-32d5-11e8-80a6-53b15310c8bc.png)
5. Try to select a date in september.

Expected behavior: Date should be selected and calendar close down.

Actual behavior: The calendar is re-rendered.

**Comment by aij** [comment] 2018-03-29 11:53
@dfahlander You seem to be running in to #361 .

**Comment by pbreah** [comment] 2018-08-27 01:40
I tested this on mobile, and it still happens on the latest release 1.6.0

I wanted to share a simpler solution: add the prop **preventOpenOnFocus** to true. It works as expected on mobile.

**Comment by ankitkapoor2493** [comment] 2019-09-11 18:14
Still facing this issue in 16.9.0 version

**Comment by olayenca** [comment] 2019-09-24 08:23
My DatePicker on desktop was wrapped inside a label and wont close on select, calling `event.preventDefault()` in onChange resolved mine.
https://github.com/Hacker0x01/react-datepicker/issues/1012#issuecomment-515350758

**Closed** 2020-04-05 10:15 UTC
Labels: needs more info, wontfix
