### ISSUE TITLE
Warning - cn: Support for defaultProps will be removed from function components in a future major release. Use JavaScript default parameters instead.

### ISSUE THREAD

**Issue by si-rg-frontend** [Hacker0x01/react-datepicker#4488] opened 2024-01-31 11:13 UTC
Getting this warning when trying to use react-datepicker in Next.js 14.0.1
```
cn: Support for defaultProps will be removed from function components in a future major release. Use JavaScript default parameters instead.
    at cn (webpack-internal:///(app-pages-browser)/./node_modules/react-datepicker/dist/react-datepicker.min.js:1:95435)
    at t (webpack-internal:///(app-pages-browser)/./node_modules/react-datepicker/dist/react-datepicker.min.js:1:95961)
```
Please see this !

**Comment by martijnrusschen** [comment] 2024-01-31 12:44
Duplicate of https://github.com/Hacker0x01/react-datepicker/issues/4477

**Closed by martijnrusschen** 2024-01-31 12:44 UTC
