### ISSUE TITLE
Close calendar on change of focus

### ISSUE THREAD

**Issue by sabina4** [Hacker0x01/react-datepicker#1170] opened 2017-12-12 07:04 UTC
How can I close the datepicker's calendar when user enters another input?

Scenario:
User enters datepicker, calendar opens, without choosing any date, user clicks on another input, the calendar doesn't close and the focus returns to the datepicker

**Comment by alex-shamshurin** [comment] 2017-12-13 21:39
You can save a reference to a date picker itself, and pass it to another component and when you need use `ref.setOpen(false)`

**Comment by aij** [comment] 2017-12-14 14:17
It should normally close when clicking outside the calendar. See the demo page.

What is the other input you are testing with? Is it react-select?

**Comment by sabina4** [comment] 2017-12-14 14:36
@aij yes react-select

**Comment by rafeememon** [comment] 2017-12-14 15:12
Closing as a dupe of https://github.com/Hacker0x01/react-datepicker/issues/730

**Closed by rafeememon** 2017-12-14 15:12 UTC
