### ISSUE TITLE
Uncaught TypeError: Cannot read property 'appendChild' of null

### ISSUE THREAD

**Issue by ConAntonakos** [Hacker0x01/react-datepicker#354] opened 2016-02-13 00:08 UTC
Not sure why this is happening. I followed the demo example exactly to make sure it wasn't anything I specifically misconfigured, but still getting the error. I would appreciate any assistance. Thank you!

**Comment by rafeememon** [comment] 2016-02-13 00:11
@ConAntonakos, please give us the steps to reproduce this issue

**Comment by ConAntonakos** [comment] 2016-02-13 00:14
Hey, @rafeememon. Thanks for your response. I'm simply instantiating a React component <DatePicker />, and when I go to click the <input> HTML element, the error fires and the calendar does not open. The "selected" prop works properly, though.

**Comment by rafeememon** [comment] 2016-02-13 00:26
@ConAntonakos, can you show us the code that is using the datepicker?

**Comment by ConAntonakos** [comment] 2016-02-13 00:30
Sure. I'm using `react-router` to render JSX view, and I'm placing the `<FormDatepicker />` on the page.

```
import React from 'react';
import merge from 'lodash.merge';
import moment from 'moment';

import Datepicker from 'react-datepicker';
import 'react-datepicker/dist/react-datepicker.css';

var FormDatepicker = React.createClass({
  displayName: 'Example',

  getInitialState: function() {
    return {
      startDate: moment()
    };
  },

  handleChange: function(date) {
    this.setState({
      startDate: date
    });
  },

  render: function() {
    return <Datepicker
        selected={this.state.startDate}
        onChange={this.handleChange} />;
  }
});

export default FormDatepicker;
```

**Comment by rafeememon** [comment] 2016-02-13 00:59
I'm able to run the code you posted in one of my apps without any issues.  Any other info you can provide would be great.  Ideally, if you can create a sample project that has the minimum code needed to repro this, we can narrow this down quickly.

**Comment by rafeememon** [comment] 2016-02-13 16:50
Just thought of something -- are your scripts being loaded in head or body?  If they're in head and running immediately, the document won't be available yet and the appendChild call will fail.

**Comment by ConAntonakos** [comment] 2016-02-13 17:42
@rafeememon Ah, that might be it! I do have the bundled script files running in head. Is that typically not advised?

**Comment by rafeememon** [comment] 2016-02-13 17:48
Not sure what is typically advised for react apps -- it would work if you start the app only on document.ready, but I find it easier just to include the script right before the closing body tag.

**Comment by karydja** [comment] 2016-02-14 22:28
+1 for this same issue. The problem seems to be with `react-tether`, precisely in [this line](https://github.com/souporserious/react-tether/blob/master/src/TetherComponent.jsx#L108), that returns `null` when it should default to `document.body`, according to [it's documentation](https://github.com/souporserious/react-tether#renderelementto-proptypesany).

**Comment by rafeememon** [comment] 2016-02-14 22:59
@karydja, can you give us more information about your setup, specifically whether your script is running in `<head>` or `<body>`?  I think this might be because `body` doesn't exist on `document` until it's been outputted, as indicated on this [stackoverflow question](http://stackoverflow.com/questions/20665509/javascript-document-body-undefined-if-not-preceded-by-a-document-write).  If it's in `head` can you try moving it to `body`?

**Comment by rafeememon** [comment] 2016-02-14 23:35
I think I puzzled this out -- submitted a fix at souporserious/react-tether#7

**Comment by karydja** [comment] 2016-02-15 11:02
@rafeememon I'm using the `DatePicker` component (with it's basic configuration) inside another component. The script is inside the `<head>` tag and, when I move it to the end of the `<body>` tag, it really works like a charm.

I tried to use previous versions (with the javascript inside `<head>`), but with the same error ):

**Comment by martijnrusschen** [comment] 2016-02-15 11:05
Ah yes that looks like the same issue. Moving the scripts to the end of the body solves it for now, but souporserious/react-tether#7 should fix in a more stable way.

**Closed** 2016-02-16 10:21 UTC
Labels: bug

**Comment by rafeememon** [comment] 2016-02-16 12:26
Should be fixed in v0.23.1

**Comment by MartinHDB** [comment] 2017-10-26 09:51
Same issue when I am calling unit test with enzyme:
```
this.picker = this.component.find(DatePicker).first();
this.day = this.picker.find('.react-date-picker__button__input__day').first();
this.day.simulate('change', { target: { value: 10 } });
```

**Comment by zakariasafidibe** [comment] 2020-04-17 14:36
whene you use Lazy-Loading you should not improt  **moduleExemple.ForRoot()** in your feature module.
So : 
`RootModule : `
imports: [
...
moduleExemple.ForRoot() , 
....
]
`feature module:`
imports: [
...
moduleExemple , 
....
]


GOOD LUCK .
