### ISSUE TITLE
inline mode does not redisplay properly

### ISSUE THREAD

**Issue by MaloneyT** [Hacker0x01/react-datepicker#743] opened 2017-02-21 18:19 UTC
In the latest release (0.41.1) in inline mode (\<DatePicker inline />) the calendar does not refresh properly after multiple date selections.

Steps to reproduce bug:
1.  open datePicker and click on a day:  the day is shown as selected
2.  move to another month (forwards or backwards) and click on a day:  the day clicked is NOT highlighted as expected

version 0.40.0 works properly

**Comment by martijnrusschen** [comment] 2017-02-25 13:18
Hmm, it seems 0.41 introduced some regressions that weren't in 0.40. Hopefully someone is able to find the root cause, so this can be fixed.

**Comment by Amauris** [comment] 2017-04-15 03:37
I created a pull request, although I'm honestly I'm not entirely sure if it's a proper fix: https://github.com/Hacker0x01/react-datepicker/pull/825

**Comment by raurfang** [comment] 2017-04-26 05:42
So, to add a bit more detail:
It looks like this bug was introduced in #673.

This:
https://github.com/Hacker0x01/react-datepicker/pull/673/files#diff-f662ae56197d5c888897a02b982f0ad3R119
causes problems when called from here:
https://github.com/github1/react-datepicker/blob/2444feea4f5d940f0de96a52fb329554c27399e3/src/datepicker.jsx#L164

The problem is caused by the `setSelected()` state changes not being applied before the `setOpen()` call is made. `setOpen()` uses `this.state` which still has the old `preSelection` value, because React's `setState()` (called in `setSelected()`) is async.

Another way to fix this is by calling `setOpen` inside a `setState` callback:
```
this.setState({}, () => this.setOpen(false))
```
This makes sure that the `setOpen()` call is made after all the previous `setState` calls finish updating the state.

**Comment by martijnrusschen** [comment] 2017-07-12 07:34
Should be fixed now

**Closed by martijnrusschen** 2017-07-12 07:34 UTC
Labels: bug
