### ISSUE TITLE
onBlur is not called when day is clicked after v2.12.0

### ISSUE THREAD

**Issue by bobmk2** [Hacker0x01/react-datepicker#2068] opened 2020-02-24 00:50 UTC
**Describe the bug**

onBlur is not called when day is clicked and closed the calendar after `v2.12.0`.

**To Reproduce**

1. Click input form and open calendar.
2. Click the day.
3. Confirm browser debug console.

**Sample code**

```typescript
import * as React from 'react';
import DatePicker from 'react-datepicker';
import * as moment from 'moment';

export const SampleDatePicker = () => {
  const handleChange = React.useCallback((next: Date) => {
    console.log('> change', moment(next).format('YYYY/MM/DD'));
  }, []);

  const handleSelect = React.useCallback((next: Date) => {
    console.log('> select', moment(next).format('YYYY/MM/DD'));
  }, []);

  const handleBlur = React.useCallback(() => {
    console.log('> blur');
  }, []);

  return <DatePicker onChange={handleChange} onSelect={handleSelect} onBlur={handleBlur} />;
};
```

**Expected behavior**

onBlur is called when day is clicked, it is same behavior as before `v2.11.0`.

**Screenshots**

#### v2.12.0

![react-datepicker_v2 12 0](https://user-images.githubusercontent.com/1858949/75123471-fcb0c280-56ea-11ea-8504-16b317b56ba9.gif)

#### v2.11.0

![react-datepicker_v2 11 0](https://user-images.githubusercontent.com/1858949/75123621-7c8b5c80-56ec-11ea-8788-3ed14cb1cb9c.gif)

**Note**

- Sorry for using unreleased version, after `v2.12.0`. :bow:
  - I only checked the latest version with `npm info react-datepicker versions`.

**Comment by jaredwindover** [comment] 2020-04-13 00:24
I realized you can use the `onCalendarClose` handler to workaround this (at least in my case).

**Comment by Naghal** [comment] 2020-05-07 14:44
I can reproduce this in my project. However, for me `onCalendarClose` is never called.

**Comment by Gluestick** [comment] 2020-09-18 12:45
Unfortunately also affected by this. This change seems to be the culprit: https://github.com/Hacker0x01/react-datepicker/pull/2027/files#diff-73642d587163f2eb4d72f0fa6ebfba02L386-L392

Reverting those few lines to their old v2.11.0 state results in `onBlur` being called after the state change. However, with `withPortal`, `onBlur` is called _before_ the state change, so I'm not sure how to go about properly fixing this.

**Comment by tu4mo** [comment] 2020-11-13 14:34
Duplicate of #2028.

**Comment by eugeneborodkin** [comment] 2021-05-23 17:24
Any solutions? This is pretty bad, the initial blurring of the control doesn't produce validation.

**Closed** 2022-04-17 06:53 UTC
Labels: wontfix

**Comment by Mahdiyeh** [comment] 2022-06-24 10:25
Unfortunately it is still not fixed and if I hack it with `showTimeInput={true}` , the value won't be recognised and still the validity will be false.

**Comment by Mahdiyeh** [comment] 2022-06-27 12:05
`!s.state.open || s.props.withPortal || s.props.showTimeInput`
In this condition onBlur will be called, so I had to trigger onBlur on input after closing the calendar:
` const handleOnCalendarClose = () => {
        pickerRef.current.input.focus();
        pickerRef.current.input.blur();
    }`

**Comment by NaN-Simon** [comment] 2025-05-12 13:46
it helped me:

```
const datePickerRef = useRef(null);

<DatePicker
    ref={datePickerRef}
    ...other props
    onChange={(update) => {
        if (update) {
             /* my code */
            setTimeout(() => datePickerRef.current.setBlur(), 10);
        }
    }}
    onCalendarClose={() => {
        setTimeout(() => datePickerRef.current.setBlur(), 10);
    }}
/>
```
