### ISSUE TITLE
The calendar is focused when tabbing out of the input field

### ISSUE THREAD

**Issue by tu4mo** [Hacker0x01/react-datepicker#2058] opened 2020-02-17 17:28 UTC
**To Reproduce**

1. Focus the input
2. Try to "tab" out of it
3. The focus goes to calendar and you have to press esc to close it

**Expected behavior**
The calendar should close and like with any input element, pressing tab in input field should focus the next element in the page. I think there should be another way to get to the calendar, if a keyboard user really wants to.

**Comment by mnsr** [comment] 2020-02-21 01:15
You can do this using `onKeyDown`.

e.g

``` javascript

  const startRef = useRef();

  const onKeyDown = (e) => {
    if (e.keyCode === 9 || e.which === 9) {
       pickupRef.current.setOpen(false);
    }
  };

  return (<DatePicker ref={startRef} onKeyDown{onKeyDown} ... />);
  
```

**Comment by tu4mo** [comment] 2020-02-22 10:22
Good to know there's a workaround. Unfortunately, now the `onBlur` event doesn't fire when tabbing out of the input field, so it needs more workarounds.

**Comment by mnsr** [comment] 2020-02-22 12:06
You could call the onBlur function after `startRef.current.setOpen(false);`

**Comment by L5eoneill** [comment] 2020-03-04 19:07
I have the same problem. On tab key press, I do 
`myRef.current.setOpen(false);`
Then I do `props.handleBlur();` which runs successfully, but the focus still doesn't move to the next element. I'm at a loss what to try next. A complication may be the nesting of the datepicker in a container in a grid...?

**Comment by BharathiBillakanti** [comment] 2020-08-07 12:36
I have an issue with calender(picker.js). After closing calender also tab is still inside calender only. Actually once we close calender it should focus input element but focus is still inside.
Can please any one help me on this.

**Comment by thetrime** [comment] 2020-11-13 12:19
This looks like it's caused by 0b64325c62695da9877a0f3e6a0800600494c60a

My expectation when I type tab in the field is that the focus is transferred out of the field and onto the next focusable item on the page, but I can understand why people might want to also move focus into the calendar for accessibility reasons. 

Since tabbing no longer dismisses the calendar, it also explains why onBlur is not firing - in index.tsx, if this.state.open is true when the blur event is received, it gets discarded.

**Comment by thetrime** [comment] 2020-11-13 12:25
If you're happy to go back in time to before 0b64325 and pin your version to 2.11.0, then you won't have any of these problems, but obviously you'll also be stuck several versions behind

**Closed** 2021-06-18 22:50 UTC
Labels: wontfix

**Comment by amber-cd** [comment] 2021-11-02 21:04
Is it possible to reopen this? We are also experiencing this issue. I would expect tabbing to first focus on the editor, allowing keyboard controls, but if pressed again to close the editor and move on to the next component, calling onBlur.

**Comment by KucharskiPiotr** [comment] 2021-11-10 09:37
> You can do this using `onKeyDown`.
> 
> e.g
> 
> ```js
>   const startRef = useRef();
> 
>   const onKeyDown = (e) => {
>     if (e.keyCode === 9 || e.which === 9) {
>        startRef.current.setOpen(false);
>     }
>   };
> 
>   return (<DatePicker ref={startRef} onKeyDown={onKeyDown} ... />);
>   
> ```

Keep in mind that `e.keyCode` and `e.which` is deprecated in favor of `e.key` (source: https://developer.mozilla.org/en-US/docs/Web/API/KeyboardEvent#obsolete_properties):

```js
   const startRef = useRef();
 
   const onKeyDown = (e) => {
     if (e.key === 'Tab') {
        startRef.current.setOpen(false);
     }
   };
 
   return (<DatePicker ref={startRef} onKeyDown={onKeyDown} ... />);
   
```
