### ISSUE TITLE
`TypeError: k.format is not a function` causing Blank Screen in Latest Version of react-datepicker

### ISSUE THREAD

**Issue by roziqinkhoeru** [Hacker0x01/react-datepicker#5124] opened 2024-09-25 01:58 UTC
**Describe the bug**
There is an issue with the latest version of `react-datepicker` doc site. The application shows a blank white screen when loading, and the browser console displays the following error:

**Expected behavior**
The site doc should render without error, and the page should not display a blank screen. The components should display as expected and allow the user to still view the documentation.

**Screenshots**
![image](https://github.com/user-attachments/assets/6e143016-2bc1-4d47-a8da-2b98c4a7d38d)

**Desktop (please complete the following information):**

- OS: Windows 11
- Browser: Arc
- Version: v.1.20.1.51458

**Smartphone (please complete the following information):**

- All Deviess

**Comment by martijnrusschen** [comment] 2024-09-25 20:30
duplicate of https://github.com/Hacker0x01/react-datepicker/issues/5108

**Closed by martijnrusschen** 2024-09-25 20:30 UTC
