### ISSUE TITLE
The onChange event not fire on time change (when included with date)

### ISSUE THREAD

**Issue by shaulnaim** [Hacker0x01/react-datepicker#1182] opened 2017-12-20 12:56 UTC
The onChange event only seems to fire when selecting a date from the picker or changing the date manually but not when the user changes the input Time. This makes it impossible to do any sort of validation on user input.

The current workaround is to set readOnly to true so that it forces users to only use the picker, but it would be ideal to also let them type into the box.

how can I detect the time manually changes?

"react-datepicker": "^0.60.2",
"react": "^15.6.1",

**Comment by vtaits** [comment] 2017-12-21 13:32
I have same problem. As temporal fix you can provide `onSelect` property that 	
duplicate of `onChange`.

```
    if (!isSameDay(this.props.selected, changedDate) || this.props.allowSameDay) {
      if (changedDate !== null) {
        if (this.props.selected) {
          changedDate = setTime(newDate(changedDate), {
            hour: getHour(this.props.selected),
            minute: getMinute(this.props.selected),
            second: getSecond(this.props.selected)
          }) // <------- bug, i need to receive time from new date instead of old selected date
        }
        this.setState({
          preSelection: changedDate
        })
      }
      this.props.onChange(changedDate, event) // <--------- fires only if day changed
    }

    this.props.onSelect(changedDate, event) // <--------- fires always
```

**Comment by juhana** [comment] 2018-08-01 14:01
A workaround is to parse the value with `onChangeRaw` and call `onChange` manually.

```
<DatePicker dateFormat="YYYY-MM-DD HH:mm"
            onChange="this.handleInputChange"
            onChangeRaw="this.handleInputChangeRaw" />

handleInputChangeRaw = e => {
  const date = moment( e.target.value, "YYYY-MM-DD HH:mm" );

  if( date.isValid() ) {
    this.handleInputChange( date );
  }
}
```

**Comment by tanajilondhefidel** [comment] 2019-04-08 13:44
`<DatePicker dateFormat="YYYY-MM-DD HH:mm" onChange={(e) => this.handleInputChange(e)}
            onChangeRaw={(e) => this.handleInputChangeRaw(e)} />`

**Closed** 2019-10-19 15:28 UTC
Labels: wontfix

**Comment by repayjustin** [comment] 2019-10-25 19:49
The issue still hasn't been resolved :-\

**Comment by cctman** [comment] 2019-12-04 18:15
Can we not get this fixed? This is seriously a core piece of functionality. I'm surprised it was overlooked.

**Comment by tzwickl** [comment] 2019-12-06 12:37
Yes this issue is still present on Android phones why can't this be fixed?

**Comment by dwightware4** [comment] 2020-04-13 19:40
This issue is a blocker. Cannot use a component that breaks basic, standard browser behavior.

**Comment by deyanskiq** [comment] 2021-06-09 07:16
any updates?

**Comment by sergeykurilov** [comment] 2023-07-13 22:10
issue still present ....

**Comment by slayer35** [comment] 2024-05-22 11:16
still no solution...

**Comment by tjmosia** [comment] 2024-11-10 20:44
This is still an open issue. Best solution would be to handle `onSelect={(event) => event.target.value}`.
