### ISSUE TITLE
How to prevent inline datepicker jump to current selected month

### ISSUE THREAD

**Issue by PanFrontend** [Hacker0x01/react-datepicker#1061] opened 2017-10-09 10:14 UTC
Hello

I'm using react-datepicker to display inline datepicker with 3 months shown. I'm looking for a way to prevent datepicker from switching months position after dates select. For now if user select dates from second or third month, datepicker will automatically switch position of months.

Do you know how to prevent that behaviour? Or should it be treated like a unwanted 'feature'? ;) 

That's no an issue on not inline datepickers (that will just disappear so user will not be affected by month change)

Here is how not wanted behaviour looks like:
![datepicker](https://user-images.githubusercontent.com/3399141/31333651-30d3bc4a-aceb-11e7-8fdb-57adc2a37fc1.gif)

**Comment by Meorne** [comment] 2017-12-01 09:14
+1
thanks

**Comment by alex-shamshurin** [comment] 2017-12-12 21:23
Hmm, if you "select" some date it should close itself. If you open the widget next time it will open on `selected` date until you specify `openToDate` property.

**Comment by sindrisig** [comment] 2017-12-20 17:18
@alex-shamshurin But the problem is that you can have the picker inline and then it never closes. I'm facing the same issue so if anybody knows a solution to this it would be much appreciated

**Comment by cmangia47** [comment] 2019-03-14 17:14
Has anyone identified a resolution to this issue?

**Comment by PanFrontend** [comment] 2019-06-18 09:55
Unfortunately, we didn't have time to investigate it. I know it lasts for the last 2 years but as it wasn't critical for our users we didn't manage to invest time. Maybe I'll be able to push this issue now up in our backlog as this component grows in importance and more users are complaining.

**Closed** 2019-12-29 10:17 UTC
Labels: wontfix

**Comment by 1jmj** [comment] 2021-02-23 11:22
this still happens in latest version...

**Comment by honam867** [comment] 2022-07-27 04:22
any update, still happens on latest version

**Comment by sergeykurilov** [comment] 2023-02-23 09:53
> Unfortunately, we didn't have time to investigate it. I know it lasts for the last 2 years but as it wasn't critical for our users we didn't manage to invest time. Maybe I'll be able to push this issue now up in our backlog as this component grows in importance and more users are complaining.

Actually, this is an important issue

**Comment by b851TYiytNCk** [comment] 2025-01-20 10:26
@michal-bednarz bumping, it is an issue in 2025 still.
