### ISSUE TITLE
There's a problem when the popup's position is "top".

### ISSUE THREAD

**Issue by yy8597** [Hacker0x01/react-datepicker#361] opened 2016-02-16 03:35 UTC
When clicking the button of increaseMonth and the height of the popup is change.  The popup of Calendar will be moved when clicking the button again. So I can't fire 'increaseMonth()'.

You can reproduce the bug by scrolling page when pupup is in bottom of page.

**Comment by rafeememon** [comment] 2016-02-16 10:24
Confirmed; I got the datepicker into a couple weird states
<img width="393" alt="screen shot 2016-02-16 at 10 23 34 am" src="https://cloud.githubusercontent.com/assets/1829450/13073579/794ceae2-d497-11e5-8ab8-3fedb7aa2ba4.png">

<img width="390" alt="screen shot 2016-02-16 at 10 23 51 am" src="https://cloud.githubusercontent.com/assets/1829450/13073574/73af67cc-d497-11e5-9edb-42dfc771988f.png">

**Comment by taxigy** [comment] 2016-02-16 19:28
I'm having the same problem. I put the `DatePicker` into a relatively positioned and constrained by width element, so the whole thing is

```jsx
<div style={{display: 'block', position: 'relative', width: '200px', zIndex: 3}}>
  <DatePicker
    className='form-control datepicker'
    dateFormat='MM/DD/YYYY'
    popoverAttachment='bottom right'
    popoverTargetAttachment='top right'
    selected={moment(category.published_at)}
    onChange={::this.setPublishDate} />
```

It behaves this way:

![react-datepicker-top-center-positioning-issue-gh-361](https://cloud.githubusercontent.com/assets/1625256/13088222/740ab554-d4fc-11e5-8aef-f8aa3a7188d7.gif)

**Comment by crunchex** [comment] 2016-03-03 01:26
Having this problem as well. I've been playing around with the tether properties, but haven't come up with a combination that serves as a workaround. If anyone finds one, please lay it down here.

**Comment by sattaman** [comment] 2016-04-08 10:15
+1 We're having the same issue

**Comment by benwill** [comment] 2016-04-11 12:00
+1 same

**Comment by bekerov** [comment] 2016-05-02 11:25
![2016-05-02_14-25-05](https://cloud.githubusercontent.com/assets/2405629/14953397/c0b0c4ba-1071-11e6-911f-08eb9e276f9e.gif)

**Comment by Rambobafet** [comment] 2016-05-09 11:55
+1

**Comment by mb21** [comment] 2016-05-10 08:34
Is there some option to force the popup to stay at "bottom" and never go to the top to avoid this bug? (I'm not sure what exactly [popoverAttachment and popoverTargetAttachment](https://hacker0x01.github.io/react-datepicker/#example-14) do, but apparently not that...)

**Comment by rafeememon** [comment] 2016-05-10 08:45
@mb21, see #470

**Comment by mb21** [comment] 2016-05-10 09:05
@rafeememon thanks, this indeed seems to sidestep the issue:

      <DatePicker
        selected={ this.props.date }
        onChange={ this.props.handleChange }
        tetherConstraints={ [] }
        />

**Comment by hakonner** [comment] 2016-05-30 13:42
Really like the component, any progress on this bug?

**Comment by rafeememon** [comment] 2016-05-30 13:54
@hakonner, we're open to contributions to fix this

**Comment by hakonner** [comment] 2016-06-03 07:48
So as already mentioned, this bug happens when the height of the calendar changes due to month change. The calendar's position does not reflect this (issue with tether component?). When the user clicks "next month", the position is moved (in correct direction). It seems like the tether reposition the calendar before the onclick is triggered, so we miss a onclick event and the calendar stays in the same month. After a couple of clicks the calendar has become correctly positioned and the component works as expected again.

The tether component is a bit complex, so haven't had the time to really understand it, but have tested a couple of things. If I delay _tether.position() execution in _updateTether, let's say 100ms and remove the for loop inside _move in TetherClass [2452] (for (var i = 0; i < this.history.length; ++i))
This seems to "fix" the problem, but I have no idea of what bi-effects this may give.

Also, the jump in the calendar can be a bit annoying to the user when flipping through several months. Another solution would be to have a max-height fix or something so the calendar would not change height, but take up a bit more space on the "lower" months. @rafeememon, how hard would this be to implement?

**Comment by jelteliekens** [comment] 2016-10-28 09:31
+1

**Comment by jbccollins** [comment] 2016-10-28 15:35
+1 Still an issue as of version ^0.33.0

**Comment by Aztek13** [comment] 2016-11-24 13:18
+1

**Comment by rpiaggio** [comment] 2016-11-26 22:06
+1 we are having this issue too. Thank you!

**Comment by Grsmto** [comment] 2017-01-09 16:13
Using `fixedHeight` prop solved that issue for me (well I'm happy with the behaviour).

**Comment by martijnrusschen** [comment] 2017-07-10 08:30
We moved away from tether. Closing this as we're not using that lib anymore.

**Comment by Nandini26** [comment] 2017-12-07 11:09
To avoid calendar shakes based on no.of weeks , we can use fixedHeight attribute. 

syntax:- <DatePicker fixedHeight 
    selected={ this.props.date }
    onChange={ this.props.handleChange }
    />

**Comment by bionicpill** [comment] 2017-12-11 22:35
This is still a bug even in the demo when the date picker is above the input box. Reproduce by shrinking your window until the date picker appears above the text input and then click back through the months and watch the calendar jump around.

**Comment by ivya-ciklum** [comment] 2018-01-11 12:20
@bionicpill have you solved it? I have exactly same issue.

**Comment by olleolle** [comment] 2018-07-12 14:15
I added `fixedHeight={true}` option and it looks better

**Closed** 2019-09-13 15:37 UTC
Labels: Hacktoberfest, bug, wontfix
