### ISSUE TITLE
Calendar shakes when position top and click next or prev month

### ISSUE THREAD

**Issue by bekerov** [Hacker0x01/react-datepicker#467] opened 2016-04-28 14:53 UTC
Hello.
Just see image. And when click from jan to dec calendar shakes

![image](https://cloud.githubusercontent.com/assets/2405629/14890121/1454560a-0d6a-11e6-820d-90013ca48894.png)

**Comment by rafeememon** [comment] 2016-04-28 15:58
Not sure what you mean by shake, but your image looks like a dupe of #361

**Closed by rafeememon** 2016-04-28 15:58 UTC
