### ISSUE TITLE
Keyboard navigation is not working on calendar

### ISSUE THREAD

**Issue by sridhar-v9** [Hacker0x01/react-datepicker#1834] opened 2019-07-24 20:49 UTC
### Expected behavior
 Even if we use the customInput the user should be able to navigate between the days or months using the keyboard
### Actual behavior
Right now not able to navigate on calendar using the key board even if i use the 

``` 
onKeyDown={(e)=>{this.props.onKeyDown(e)}}
```
### Steps to reproduce
 See the inline and custom input examples in https://hacker0x01.github.io/react-datepicker/.

Please provide any suggestions/comments

**Comment by anadutova** [comment] 2019-08-13 13:10
Duplicate of #744

**Comment by functionportal** [comment] 2019-10-17 04:01
#744 was closed due to inactivity with no resolution, so this is no longer the duplicate. Will this be resolved at any point in the future. This is an accessibility defect.

**Closed** 2020-04-28 04:16 UTC
Labels: wontfix
