### ISSUE TITLE
Add className for wrapper

### ISSUE THREAD

**Issue by fresk-nc** [Hacker0x01/react-datepicker#1040] opened 2017-09-25 15:55 UTC
Can you add some className for this div?
![react-datepicker](https://user-images.githubusercontent.com/6768490/30817981-fee79c56-a222-11e7-869f-e15e074388a2.jpg)

**Comment by hufftheweevil** [comment] 2017-09-27 15:38
I, too, am looking to control the style of the main wrapper. My biggest issue is that it takes up 100% width, so I can't put two Date Picker fields right next to each other.

**Comment by jordansykes** [comment] 2017-11-02 08:39
If you just create your own wrapper for each datepicker element then put on your styles on that, the datepicker will take up 100% of the space.  I agree it would be useful to be able to add a classname to that empty containing div though.

**Comment by aij** [comment] 2017-11-02 13:03
Duplicate of #932

**Comment by ladislavbili** [comment] 2018-04-11 11:38
Yeah I had this problem too, until it is solved I reccomend wrapping it in your own div, style and give classname to that div and then you can set its css like this:
**render example**
```
<div className="datepickerWrap">
<DatePicker/>
</div>
```
**css example**
```
.datepickerWrap div{
  width: 100%;
}
.datepickerWrap{
  width: 100%;
}
```

of course, it is up to you to style it as you want and set everything in your datepicker up, you might also want to change css of one of these guys but that situational
```
react-datepicker__time-container
react-datepicker__time
react-datepicker__time-box
react-datepicker__time-list
react-datepicker__input-container
react-datepicker-wrapper
react-datepicker__input-container
```

**Comment by seansfkelley** [comment] 2018-06-27 00:12
As a workaround, you can reasonably safely select the classless `div` using `... > div:not([class])` where `...` selects the parent `div` you control. This way, you don't need to add another layer with a class just so you can style it.

**Comment by seansfkelley** [comment] 2018-09-20 21:46
Related: #1344, #1208. Looks like this wrapper div has been causing a lot of grief.

**Closed** 2019-09-13 13:37 UTC
Labels: wontfix
