### ISSUE TITLE
Migrate to date-fns 3.0.0 or remove dependency

### ISSUE THREAD

**Issue by fsuk** [Hacker0x01/react-datepicker#4466] opened 2024-01-19 08:08 UTC
**Is your feature request related to a problem? Please describe.**
date-fns 3.0.0 improves imports allowing for smaller bundle sizes without tree shaking
attempting to use date-fns 3.0.0 alongside react-datepicker which uses 2.x.x causes errors

**Describe the solution you'd like**
Migration or branch to date-fns 3.0.0 (this would be a major release or react-datepicker) 
or
Refactor to remove this dependency

**Comment by martijnrusschen** [comment] 2024-01-19 08:11
This is a duplicate of https://github.com/Hacker0x01/react-datepicker/issues/4433. We welcome any contributions to upgrade to the latest version.

**Closed by martijnrusschen** 2024-01-19 08:11 UTC
