### ISSUE TITLE
Module not found: Can't resolve 'react-onclickoutside'

### ISSUE THREAD

**Issue by Satish789748** [Hacker0x01/react-datepicker#4122] opened 2023-07-09 11:52 UTC
"react-datepicker": "4.13.0",
    In this version getting this issue.
    error - ../../node_modules/react-datepicker/dist/react-datepicker.min.js:1:15
Module not found: Can't resolve 'react-onclickoutside'

**Comment by Zarthus** [comment] 2023-07-11 06:04
I was unable to reproduce, can you give more insights?

The dep is also visible in the 4.13 tag

**Comment by yuki0410-dev** [comment] 2024-03-24 15:49
The PR for this issue has already been merged and appears to be resolved.

( cc. @martijnrusschen )

**Closed** 2024-03-24 18:28 UTC
