### ISSUE TITLE
Example page fails to load months & years dropdown

### ISSUE THREAD

**Issue by hejiaji** [Hacker0x01/react-datepicker#2118] opened 2020-04-23 05:21 UTC
**Describe the bug**
Example page fails to load months & years dropdown

**To Reproduce**

1. Go to 'https://reactdatepicker.com/'
2. Navigate to 'Month dropdown' section
3. Click on the input under the section
4. Click the month dropdown as below
![image](https://user-images.githubusercontent.com/19968961/80061964-ef427800-8575-11ea-858e-32369b34ddf5.png)

```Error: Minified React error #290; visit https://reactjs.org/docs/error-decoder.html?invariant=290&args[]=options for the full message or use the non-minified dev environment for full errors and additional helpful warnings. ```

**Expected behavior**
The dropdown pop up shows up.

**Desktop (please complete the following information):**

- OS: MAC
- Browser Chrome
- Version 80.0.3987.163

**Comment by watery** [comment] 2020-04-24 08:58
Duplicate of #2088

**Comment by martijnrusschen** [comment] 2020-05-06 11:49
This should be fixed with #2132 merged. We will release a new version shortly.

**Closed by martijnrusschen** 2020-05-06 11:49 UTC
