### ISSUE TITLE
Datepicker breaks if you use left/right keys when default selected date is blank

### ISSUE THREAD

**Issue by ayushya** [Hacker0x01/react-datepicker#631] opened 2016-11-21 13:55 UTC
```          
<DatePicker
   placeholderText="Click to Select Date"
   selected={invoiceDate}
   onChange={ date => handleChangeInvoiceFormDate('invoiceDate', date)}
/>
```
I am using the above code, default i have chosen empty string in selected param.
When i haven't selected any date and i try using left/right keyboard key, the DatePicker Breaks and i am unable to select/update or use it unless i refresh the page.

Initial State
<img width="235" alt="screen shot 2016-11-21 at 7 23 00 pm" src="https://cloud.githubusercontent.com/assets/7705367/20485060/f7ad6ace-b01f-11e6-8793-677487e8ab9f.png">

After using left/right Key
<img width="255" alt="screen shot 2016-11-21 at 7 18 58 pm" src="https://cloud.githubusercontent.com/assets/7705367/20485084/08bba9ca-b020-11e6-9898-1f794970da4f.png">

As a hack i can initialise the value as `moment()`, but i want the user to see the placeholder instead of default current date.

**Comment by jochenberger** [comment] 2016-12-08 12:55
I can reproduce this, it also happens if the initial date is `null`, it works fine for `undefined` however.

**Comment by jochenberger** [comment] 2016-12-08 13:02
Duplicate of #607 actually

**Closed** 2016-12-08 16:14 UTC
