### ISSUE TITLE
Bug with date selection

### ISSUE THREAD

**Issue by danylomarkov** [Hacker0x01/react-datepicker#595] opened 2016-10-18 12:26 UTC
This bug occurs when datepicker is over the input and month calendars have different number of lines. Look at the video.

https://www.youtube.com/watch?v=uMKNSp3ktBs

**Comment by kaushikbarodiya** [comment] 2016-10-20 07:57
Hi danylomarkov,

Have you find any workaround for this problem?I am also facing this issue.Great if you can help.

**Comment by Hjort-e** [comment] 2016-10-20 08:03
Were having this issue exact issue too.
We can only reproduce it on one specific computer though, really wierd

**Comment by kaushikbarodiya** [comment] 2016-10-20 08:10
I have used fixedHeight for workaround.

**Comment by rafeememon** [comment] 2016-10-21 13:49
Dupe of https://github.com/Hacker0x01/react-datepicker/issues/361

**Closed by rafeememon** 2016-10-21 13:49 UTC
