### ISSUE TITLE
Warning: nr: Support for defaultProps will be removed from function components in a future major release. Use JavaScript default parameters instead.

### ISSUE THREAD

**Issue by shyk001** [Hacker0x01/react-datepicker#4475] opened 2024-01-27 09:39 UTC
This error occurs when using nextjs 14.0.4:

```
Warning: nr: Support for defaultProps will be removed from function components in a future major release. Use JavaScript default parameters instead.
  at nr (webpack-internal:///(ssr)/./node_modules/react-datepicker/dist/es/index.js:2931:58)
  at a (webpack-internal:///(ssr)/./node_modules/react-datepicker/dist/es/index.js:2959:16)
  at DateRangeInput (webpack-internal:///(ssr)/./src/components/atoms/DateRangeInput.tsx:16:78)
  ...
```

**Comment by martijnrusschen** [comment] 2024-01-31 12:44
/duplicate https://github.com/Hacker0x01/react-datepicker/issues/4477

**Comment by martijnrusschen** [comment] 2024-01-31 12:44
Duplicate of https://github.com/Hacker0x01/react-datepicker/issues/4477

**Closed by martijnrusschen** 2024-01-31 12:44 UTC
