### ISSUE TITLE
Uncaught TypeError: Cannot read property 'clone' of undefined

### ISSUE THREAD

**Issue by nosoosso** [Hacker0x01/react-datepicker#192] opened 2015-09-26 14:44 UTC
When I run this:

```jsx
var React = require('react');
var DatePicker = require('react-datepicker');

var Example = React.createClass({

  handleChange: function() {
    this.setState({
      dummyDate: '2015-09-27'
    });
  },

  render: function() {
    return <DatePicker onChange={this.handleChange} />;
  }
});
```

I got this:

`Uncaught TypeError: Cannot read property 'clone' of undefined`

Should I not call setState() in onChange callback?

**Comment by nosoosso** [comment] 2015-09-26 14:57
Ah, it looks like the same issue as #187.

**Comment by martijnrusschen** [comment] 2015-11-08 11:24
Yep duplicate of #187

**Closed by martijnrusschen** 2015-11-08 11:24 UTC
