### ISSUE TITLE
After update from version 0.40.0 calendar not update selected date

### ISSUE THREAD

**Issue by AntonovAv** [Hacker0x01/react-datepicker#843] opened 2017-04-26 11:52 UTC
Calendar display old selected date  if i put new `selected` prop to calendar.
```
<DatePicker
        ref={this.onDatePickerRef}
        openToDate={this.state.openDate}
        onMonthChange={this.onMonthChange}
        customInput={<SelectedDate/>}
        popoverTargetOffset='0 0'
        dateFormat={isSelectedCurrentYear ? DATE_FORMAT_FOR_CURRENT_YEAR : DATE_FORMAT}
        dateFormatCalendar='MMMM'
        {...this.props}
        selected={this.state.selectedDate}
        onChange={this.onSelectedDateChange}
        filter={this.datesFilter}
        forceShowMonthNavigation={true}
      >
        <YearsSelector onChange={this.onYearChange} year={this.state.openDate.year()}/>
      </DatePicker>
```
prev selected date 01 april
![image](https://cloud.githubusercontent.com/assets/11208532/25433020/917e8dce-2a8f-11e7-8c0a-9d7f8e7cfb21.png)

prev selected date 30 april
![image](https://cloud.githubusercontent.com/assets/11208532/25433040/acbc6728-2a8f-11e7-94d5-43b91fe40e15.png)

How you seen. On filter prop calendar reacts and disable days

**Comment by JorgenEvens** [comment] 2017-06-10 13:49
We are seeing something similar in our application.

**Comment by malyfko** [comment] 2017-06-27 14:34
@JorgenEvens Thanx, you saved me life! 😃

**Comment by alex-shamshurin** [comment] 2017-06-27 16:03
`OpenToDate` property always take precedence over `selected` value. Does not specify `openToDate` 

> The calendar switches back to the old date

it's normal behaviour, calendar will scroll on `openToDate`

**Comment by malyfko** [comment] 2017-06-27 16:07
@alex-shamshurin I'm using 'inline' option, `OpenToDate` shouldn't even be considered

**Comment by alex-shamshurin** [comment] 2017-06-27 20:42
if so, do not use it, otherwise it will be scrolled to `openToDate` value.

**Comment by JorgenEvens** [comment] 2017-06-27 22:30
@alex-shamshurin So what you are suggesting is that the behaviour on the [inline example](https://hacker0x01.github.io/react-datepicker/#example-25) is intended behaviour?

To be clear I was literally using the component as specified earlier (`<DatePicker inline={true} selected={selectedDate} />`), not setting `openToDate` to any value at all when I ran into this issue.

If this is intended I think that the example should be fixed and the documentation should clearly state how `inline` should be used, because at this point even your explanation confuses me on the purpose of `openToDate` in the context of an `inline` calendar.

**Comment by alex-shamshurin** [comment] 2017-06-28 06:19
@JorgenEvens So what is wrong with the inline example? Could you provide more info, please?

**Comment by JorgenEvens** [comment] 2017-06-28 07:32
@alex-shamshurin I've added [steps to reproduce](https://github.com/Hacker0x01/react-datepicker/issues/843#issuecomment-307566284) in the second comment of this thread.

**Comment by alex-shamshurin** [comment] 2017-06-28 07:39
Yes, I see this

**Comment by malyfko** [comment] 2017-06-28 07:42
@alex-shamshurin the problem is described by @AntonovAv  - after clicking on the `switch month` arrow, selecting date works as some kinda 'stack' and takes value I ckicked 2 steps ago, for example.

**Comment by martijnrusschen** [comment] 2017-07-10 08:22
Is this still an issue?

**Comment by martijnrusschen** [comment] 2017-07-12 07:34
Should be fixed now.

**Closed by martijnrusschen** 2017-07-12 07:34 UTC
Labels: bug
