### ISSUE TITLE
Can not choose year or month?

### ISSUE THREAD

**Issue by hellokitty111** [Hacker0x01/react-datepicker#233] opened 2015-11-17 08:42 UTC
now, we can only choose month or year by clicking the arrow.if we want to choose 1990, we can only input 1990-01-01?

**Comment by KeitIG** [comment] 2015-11-17 15:06
see #90 for year selection.

**Comment by martijnrusschen** [comment] 2015-12-07 12:38
Duplicate of #90

**Closed by martijnrusschen** 2015-12-07 12:38 UTC
