### ISSUE TITLE
Date selection not working when wrapped under a web component with shadow DOM

### ISSUE THREAD

**Issue by pusulurm** [Hacker0x01/react-datepicker#1928] opened 2019-10-04 04:30 UTC
I found this component more flexible and wanted to use in my react application. Our application is wrapped as a web component and this component seems to not work under shadow DOM. Following is a code sample i prepared and please take a look .

`
// Component code
import React, {useState} from 'react';
import DatePicker from 'react-datepicker';

function MyDatePicker() {
  const [startDate, setStartDate] = useState(new Date());

  const onDateChange = (date) =>{      
      setStartDate(date);
  };

  return (      
      <DatePicker
          selected={startDate}
          onChange={onDateChange}
          minDate={new Date()}
          showTimeSelect
          placeholderText="Select a date"
          dateFormat="dd-MMM-yyyy HH:mm:ss"
          shouldCloseOnSelect={true}
      />      
  );
}
export default MyDatePicker;

// Web component definition
import React from 'react';
import ReactDOM from 'react-dom';
import MyDatePicker from './myDatePicker';

class DateWebComponent extends HTMLElement {
    constructor() {
        super();
        this.shadow = this.attachShadow({ mode: 'open' });
    }

    connectedCallback() {
        const link = document.createElement('link');
        link.type = 'text/css';
        link.href = './react-datepicker.css';
        link.rel = 'stylesheet';
        this.shadow.appendChild(link);

        const appArea = document.createElement('div');
        this.shadow.appendChild(appArea);
        retargetEvents(this.shadow);
        ReactDOM.render(<MyDatePicker />, appArea);
    }

    disconnectedCallback() {
        ReactDOM.unmountComponentAtNode(this);
    }
}

customElements.define('my-date', DateWebComponent);
`

Finally used it in index.html

` <div id="root">
      <pwi-date></pwi-date>
    </div>`
 

In this case, there is no onChange event fired from the calender component. Popup gets closed on click.
If I remove shadow DOM from component, it seems to be working fine. 
Please suggest

**Comment by nermand** [comment] 2019-10-23 14:57
The problem is with `react-onclickoutside`, it seems. 
There is an open PR that should fix this, once it gets merged to master:
https://github.com/Pomax/react-onclickoutside/pull/324

**Closed** 2020-05-06 19:04 UTC
Labels: wontfix
