### ISSUE TITLE
Mobile device on scroll calendar goes away

### ISSUE THREAD

**Issue by fden** [Hacker0x01/react-datepicker#512] opened 2016-06-23 14:49 UTC
Hi!

If you click the date input and the calendar picker shows up, but if you scroll the screen then the calendar picker goes away. How can I resolve this?

Thank you.

**Comment by preacher2041** [comment] 2016-07-08 08:38
Having the same issue, its a bit frustrating for mobile users. That and the fact the keyboard still appears.

**Comment by mattjstar** [comment] 2016-07-31 18:47
@preacher2041 you can get rid of the keyboard by setting a `readOnly` prop to true.

I'm also having the issue though where when scrolling sometimes the calendar disappears. When looking at the DOM, the class name `react-datepicker-ignore-onclickoutside` on the child input prop gets removed sometimes on scroll.

**Comment by skywickenden** [comment] 2017-01-11 15:36
+1 This is a problem on mobile.

**Comment by jkowens** [comment] 2017-04-03 20:21
+1 If the date input lost focus when clicking outside, I think that would resolve the issue. I can't figure out a way to force that to happen tho.

**Comment by redaben** [comment] 2017-11-19 10:37
+1

**Comment by skinread** [comment] 2018-06-28 04:11
This still seems to be an issue: on any touch event outside of the input field or date picker, the calendar is hidden, even if only a swipe event and focus remains on the input. 
Mobile users are unlikely to see the full calendar in viewport, especially when keyboard is open, so makes it extremely difficult to use.

Any opportunity to address this one after all this time?

**Comment by MedianHansen** [comment] 2018-09-14 13:28
I made a fix for this and is sending in a pull request.

**Comment by sanderlenaerts** [comment] 2018-10-02 12:56
Any idea if they plan on merging and releasing this? I see your PR has some merge conflcits. @MedianHansen

**Comment by pvolodymyr** [comment] 2018-10-03 11:57
Hi, the issue is still here, when it could be fixed?

**Closed** 2019-09-13 13:37 UTC
Labels: wontfix
