### ISSUE TITLE
Minified version is used as main entry in package.json

### ISSUE THREAD

**Issue by Phyks** [Hacker0x01/react-datepicker#968] opened 2017-07-26 09:12 UTC
Hi,

When building an app with Webpack and using react-datepicker as a dependency, it seems the whole minified version of react-datepicker is picked in the bundle.

![a](https://user-images.githubusercontent.com/3856586/28613514-d49842d0-71f2-11e7-84b6-b55223a596eb.png)

It seems that this is coming from the fact that the `main` value in the package.json is set to the minified version. On the contrary, most other modules just the unminified version in the package.json, see for instance [moment](https://github.com/moment/moment/blob/develop/package.json).

I would tend to think providing the minified version is not as efficient, as it becomes more difficult to do some optimizations on the imported code, such as providing context to Webpack and so on. Plus it can be a source of issues if an [aggressive minification is done twice](https://github.com/nervgh/angular-file-upload/issues/703).

Thanks!

**Comment by aij** [comment] 2017-07-26 13:23
What did you use to generate that nice graphic?

This seems like a duplicate of #405.

For now, as a workaround, I think you can change your import to `import DatePicker from 'react-datepicker/lib/datepicker';` to get the unbundled/unminified version.

**Comment by Phyks** [comment] 2017-07-26 13:36
I used https://github.com/th0r/webpack-bundle-analyzer, I really like this software, it gives awesome insights on your bundles :)

Sorry for the duplicate :/ I did do a search prior to opening this ticket, but I completely missed this one.

Thanks a lot for the workaround! =)

![capture d ecran 2017-07-26 a 15 36 33](https://user-images.githubusercontent.com/3856586/28624083-3c7569ee-7218-11e7-9ef1-1064a4b1b762.png)

**Comment by martijnrusschen** [comment] 2017-12-17 16:11
Closing since it's a dupe :)

**Closed by martijnrusschen** 2017-12-17 16:11 UTC
