### ISSUE TITLE
Month Navigation Arrows do not show on Safari

### ISSUE THREAD

**Issue by GilliganL** [Hacker0x01/react-datepicker#3082] opened 2021-06-29 15:45 UTC
**Describe the bug**
The month navigation arrows are not present on Safari.

**To Reproduce**
Open the datepicker popper in Safari and look for the arrows that are used to change months.

**Expected behavior**
The arrows should be displayed the same as Chrome.

**Screenshots**

**Desktop (please complete the following information):**

- OS: [e.g. iOS] Macbook Big sur 11.4
- Browser [e.g. chrome, safari] Safari
- Version [e.g. 22] 14.1.1

**Smartphone (please complete the following information):**

**Additional context**
Changing the styling of the span that has the pseudo element resolves the issue. (I add height and width 100% to the span and then changed the size and positioning of the :before element)

**Comment by HintDevelopment** [comment] 2021-06-30 13:03
Also came across this issue today. Simply going to the demo site is enough to reproduce the issue: https://reactdatepicker.com

**Comment by Ugoku** [comment] 2021-07-21 07:14
Duplicate of #3028

**Closed** 2022-04-18 15:53 UTC
Labels: wontfix
