### ISSUE TITLE
Date picker offset dates incorrectly is selected props receives a non-moment object

### ISSUE THREAD

**Issue by pablolmiranda** [Hacker0x01/react-datepicker#627] opened 2016-11-16 01:14 UTC
You can see the issue on the 'Clear datepicker input' example.
After clear the component, the selected field will receive a null value. That will create a strange behavior inside the DatePicker that will wrongly offset the dates.
The Calendar component will understand the week starts on Saturday and not Monday for `en` locale, creating a cascade of wrong day assignment to each Day component.

**Comment by rafeememon** [comment] 2016-11-16 03:04
I think it is intended behavior that clearing the date input propagates a `null` value; since the component uses moment.js objects for the API, there aren't really any other possibilities.  Can you give a concrete sample app that shows:

* Sample code
* Expected behavior
* Actual behavior

**Comment by pablolmiranda** [comment] 2016-11-16 04:27
@rafeememon, I will use the 'Clear datepicker input' as a base example. We can change the handler function to:
```
  handleChange (date) {
    console.log(date && date.valueOf()); // This line will show the problem
    this.setState({
      startDate: date
    })
  },
```

Assuming you choose 10/27/2016 on the calendar, the value for `date.valueOf()` will be 1477526400000. When you build a new `Date` object using this value you will receive the follow output `Wed Oct 26 2016 17:00:00 GMT-0700 (PDT)`. 

I would expect a timestamp related to 10/27/2016 and not 10/26/2016. 

Makes sense?

**Comment by Stanback** [comment] 2016-12-16 00:36
Looks like this is still an issue

**Comment by vladimir-konnov** [comment] 2017-06-28 14:00
Guys, I have the same issue with wrong date.
1) I scroll months say from June to August.
2) Then for instance I click 08/01/2017 and get 07/31/2017.
Has anyone found a fix for this issue with wrong date?
P.S. Seems that scrolling months is essential

**Comment by romanveryovkin** [comment] 2017-10-14 17:44
Hi guys, I have the same story...does anybody have a workaround here?

**Comment by vladimir-konnov** [comment] 2017-10-15 13:13
@romanveryovkin I have found workaround for my case:
```
moment.utc(date.valueOf() + date.utcOffset() * 60000)
```
I don't know if it works in your case or in every case.

**Comment by mdo5004** [comment] 2018-01-30 21:08
@vladimir-konnov Did not work in my case. It looks like the issue _is_ with the time of day, however. For example, picking 02/02/2018 where I am gives me 02/01/2018 at 19:00:00 and I am GMT-0500. This means it's probably selecting 02/02/2018 at 00:00:00 and then accounting for the fact that I am 5 hours ahead of that.

**Comment by Definence** [comment] 2018-07-25 10:56
@vladimir-konnov, works for me
`moment.utc(date.valueOf() + date.utcOffset() * 60000)`

**Comment by martijnrusschen** [comment] 2018-11-17 13:20
Moment.js was removed in #1527, starting v2.0.0, this package doesn't use Moment anymore.

**Closed by martijnrusschen** 2018-11-17 13:20 UTC
