### ISSUE TITLE
React 16 Update

### ISSUE THREAD

**Issue by Shadowman4205** [Hacker0x01/react-datepicker#1053] opened 2017-10-03 14:28 UTC
Hello, i get this warning,

warning "react-datepicker@0.55.0" has incorrect peer dependency "react@^0.14.0 || ^15.0.0".
warning "react-datepicker@0.55.0" has incorrect peer dependency "react-dom@^0.14.0 || ^15.0.0".

will be any updates?

**Comment by aij** [comment] 2017-10-03 14:45
Are there any problems besides the warning?

**Comment by Shadowman4205** [comment] 2017-10-03 14:52
At first sight no i did not find any problem

**Comment by bjankord** [comment] 2017-10-04 18:17
There is an open issue around react 16 support here: https://github.com/Hacker0x01/react-datepicker/issues/972

**Comment by aij** [comment] 2017-10-04 19:22
Duplicate of #972

**Closed by aij** 2017-10-04 19:22 UTC
