### ISSUE TITLE
Module not found: Can't resolve 'react-datepicker/dist/react-datepicker.css' in v2.9.0

### ISSUE THREAD

**Issue by hiredgun** [Hacker0x01/react-datepicker#1882] opened 2019-08-29 10:09 UTC
**Describe the bug**
Looks like the package folder is missing `dist` folder after 2.9.0 release causing webpack build to fail due to the missing 'react-datepicker/dist/react-datepicker.css' file

![image](https://user-images.githubusercontent.com/2885483/63931299-4fb7fe80-ca55-11e9-8809-3b9e18bddd2d.png)

**To Reproduce**

Install 2.9.0 version and import 'react-datepicker/dist/react-datepicker.css' file in one of your components

**Desktop (please complete the following information):**

- OS: Mac

**Additional context**
Node: 12.9.0
NPM: 6.10.2

**Comment by thitoo** [comment] 2019-08-29 10:13
same here

**Comment by srMarquinho** [comment] 2019-08-29 10:14
Major issue for us atm.

**Comment by martijnrusschen** [comment] 2019-08-29 10:18
@mxschmitt Any idea what went wrong here. This might be caused by the refactoring of the release process.

**Comment by mxschmitt** [comment] 2019-08-29 10:57
> @mxschmitt Any idea what went wrong here. This might be caused by the refactoring of the release process.

I guess it it's because of my refactoring. I will investigate now

**Comment by tuttiflirty** [comment] 2019-08-29 11:40
I'm observing the same issue on @2.0.0 also. I managed to get rid of the problem locally with `npm install style-loader css-loader --save` but I still have this issue on Cicrcle CI as 

```
yarn run v1.17.3
$ react-scripts build
Creating an optimized production build...
Failed to compile.

Module not found: Error: Can't resolve 'react-datepicker/dist/react-datepicker.css' ...
```

**Comment by JohnLyonJunior** [comment] 2019-08-29 11:42
same problem on @2.1.0. Hopefully you guys can resolve this)

**Comment by junmich** [comment] 2019-08-29 12:22
same problem here, any fix or workaround that you could recommend? Major issue in our deployment now.

**Comment by NwogeEberechi** [comment] 2019-08-29 12:28
same problem, I am facing the same issue in our deployment

**Comment by vitaliyzh** [comment] 2019-08-29 12:32
Same problem

**Comment by ni3k** [comment] 2019-08-29 12:58
same problem

**Comment by mxschmitt** [comment] 2019-08-29 13:00
I created here a Pr, should fix the build process: https://github.com/Hacker0x01/react-datepicker/pull/1883

But I'm sorry, I don't have much rollup knowledge :/

**Comment by tuttiflirty** [comment] 2019-08-29 13:19
Thank you for the patch v2.9.1 @mxschmitt , but it doesn't seem to work for me neither Same error.

**Comment by martijnrusschen** [comment] 2019-08-29 14:05
Can you try this again with v2.9.3?

**Comment by tuttiflirty** [comment] 2019-08-29 14:18
Thx @martijnrusschen ! All working now 💯

**Comment by martijnrusschen** [comment] 2019-08-29 14:41
Fixed by 98fa95162b51ac523da37c8de66fae05d64ef717. Thanks all!

**Closed by martijnrusschen** 2019-08-29 14:41 UTC
Labels: bug

**Comment by flameuzumo** [comment] 2019-09-10 10:53
This package use to work in meteor.js. I install it using: meteor npm install --save react-datepicker
But now I get an error that references react-datepicker.css, here it is:

`/home/2in/Meteor1.6/meteor10-Hydrate/Atrade/node_modules/react-datepicker/dist/react-datepicker.css:1
(function (exports, require, module, __filename, __dirname) { .react-datepicker-popper[data-placement^="bottom"] .react-datepicker__triangle, .react-datepicker-popper[data-placement^="top"] .react-datepicker__triangle, .react-datepicker__year-read-view--down-arrow,
                                                              ^

SyntaxError: Unexpected token .
    at createScript (vm.js:80:10)
    at Object.runInThisContext (vm.js:139:10)
    at Module._compile (module.js:616:28)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at npmRequire (/home/2in/Meteor1.6/meteor10-Hydrate/Atrade/.meteor/local/build/programs/server/npm-require.js:133:10)
    at Module.useNode (packages/modules-runtime.js:664:18)
    at react-datepicker.css (packages/modules.js:433:8)
    at fileEvaluate (packages/modules-runtime.js:336:7)
    at Module.require (packages/modules-runtime.js:238:14)
    at Module.moduleLink [as link] (/home/2in/.meteor/packages/modules/.0.13.0.ibssab.6e4t++os+web.browser+web.browser.legacy+web.cordova/npm/node_modules/reify/lib/runtime/index.js:38:38)
    at SearchPurchaseHistory.jsx (imports/ui/components/SearchPurchaseHistory.jsx:1:226)
    at fileEvaluate (packages/modules-runtime.js:336:7)
    at Module.require (packages/modules-runtime.js:238:14)
    at Module.moduleLink [as link] (/home/2in/.meteor/packages/modules/.0.13.0.ibssab.6e4t++os+web.browser+web.browser.legacy+web.cordova/npm/node_modules/reify/lib/runtime/index.js:38:38)
    at router.jsx (imports/ui/router.jsx:1:8256)
    at fileEvaluate (packages/modules-runtime.js:336:7)
    at Module.require (packages/modules-runtime.js:238:14)
Exited with code: 1
Your application is crashing. Waiting for file change.`

Any ideas? Is this a bug?
Is there a react and meteor specific datepicker I can use if this can't be resolved?

**Comment by izaakf** [comment] 2019-12-02 18:15
getting this error on v2.10.1

**Comment by sommesh** [comment] 2020-05-02 08:16
getting the same error on v2.14.1.
Any solutions?

**Comment by izaakf** [comment] 2020-05-02 12:51
@sommesh i never came across a stable solution so I moved to a different package unfortunately

**Comment by sommesh** [comment] 2020-05-02 13:31
Okay, kindly let me know does that different package has accessibility support? 

Anyway, I did a workaround to fix this.
Just moved the file `node_modules/react-datepicker/dist/react-datepicker.css` to my local src folder and imported it.

**Comment by Dror-Bar** [comment] 2021-01-05 09:22
@sommesh I used the same solution. css file didn't load after building. Had to move the file to my local src folder and import it from there.

**Comment by mxschmitt** [comment] 2021-01-05 09:46
It's weird since its there somehow: https://unpkg.com/react-datepicker@3.3.0/dist/react-datepicker.css

**Comment by Dror-Bar** [comment] 2021-01-05 10:10
@mxschmitt I'm using version 2.10.0. Could it be related? I didn't want to upgrade yet because 1. I wasn't sure if any breaking changes would affect me 2. I wasn't confident upgrading will fix the bug.
If this bug only happens on versions 2x then I guess it's not a real issue anymore, however I cannot confirm this myself.

**Comment by minhhunghuynh1106** [comment] 2021-06-06 03:25
I have resolved this problem
Type `npm install react-datepicker --save` in terminal
Then import these in your component
```
import DatePicker from "react-datepicker";
import "react-datepicker/dist/react-datepicker.css";
```
Usage
```
const Example = () => {
  const [startDate, setStartDate] = useState(new Date());
  return (
    <DatePicker selected={startDate} onChange={(date) => setStartDate(date)} />
  );
};
```
Good luck :)

**Comment by patricktan98** [comment] 2021-07-22 16:11
I still encounter this problem in production build, may I know how's the update?

**Comment by thilinadinith** [comment] 2022-08-31 12:55
same problem

**Comment by Enache-Ionut** [comment] 2022-09-15 20:22
same problem here

**Comment by minhld-ows** [comment] 2022-09-26 04:02
the problem still existed in @types/react-datepicker v4.4.2

**Comment by jl0zano** [comment] 2022-09-30 23:11
> You need to install both "@types/react-datepicker" & "react-datepicker"

Thanks! This was my issue. I had only installed "@types/react-datepicker". Worked great after installing "react-datepicker" too.

**Comment by jhonvy95** [comment] 2022-12-14 05:25
> You need to install both "@types/react-datepicker" & "react-datepicker"

thankss so much, this worked for me

**Comment by AbhiSmith** [comment] 2024-01-26 18:56
just run `npm install --save @types/react-datepicker`

**Comment by Rob-ot** [comment] 2025-02-26 23:47
For me, this was because I was on an old version of webpack that didn't support the wildcard syntax react-datepicker uses to export the css files in package.json.

e.g. react-datepicker package.json includes this: `"./dist/*.css": "./dist/*.css"` which webpack didn't support on older versions.

Happy hacking 😃
