### ISSUE TITLE
Installation via rails-asset seems to be broken

### ISSUE THREAD

**Issue by Failproofshark** [Hacker0x01/react-datepicker#305] opened 2016-01-14 15:06 UTC
This might be related to error #303 in that the latest version (0.18.0) via rails-assets seems to be broken as well. Installing any version past 0.15.2 results in the pipeline breaking reporting javscript asset could not be found after adding `//= require react-date-picker` to my application.js

This is my application.js
```
//= require jquery
//= require jquery_ujs
//= require turbolinks
//= require react
//= require react_ujs
//= require components
//= require moment
//= require react-date-picker
//= require_tree .
````

**Comment by martijnrusschen** [comment] 2016-01-14 15:11
Yup looks like the same problem.

**Comment by RSO** [comment] 2016-01-15 14:31
Closing as dupe of #303

**Closed by RSO** 2016-01-15 14:31 UTC
Labels: bug
